CREATE TABLE `signal_journal` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sessionToken` varchar(128) NOT NULL,
	`symbol` varchar(32) NOT NULL,
	`instrumentToken` varchar(128),
	`direction` enum('BUY','SELL') NOT NULL,
	`layer` varchar(64) NOT NULL,
	`confidence` float NOT NULL,
	`entryPrice` float NOT NULL,
	`suggestedSl` float,
	`suggestedTarget` float,
	`atr` float,
	`regime` varchar(32),
	`vixLevel` float,
	`oiBias` varchar(16),
	`outcome` enum('traded','rejected','pending') NOT NULL DEFAULT 'pending',
	`rejectReason` varchar(128),
	`tradeId` int,
	`exitPrice` float,
	`pnl` float,
	`exitReason` varchar(64),
	`holdDurationMs` bigint,
	`maxFavorableExcursion` float,
	`maxAdverseExcursion` float,
	`signalAt` timestamp NOT NULL DEFAULT (now()),
	`outcomeAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `signal_journal_id` PRIMARY KEY(`id`)
);
