import { systemRouter } from "./_core/systemRouter";
import { publicProcedure, router } from "./_core/trpc";
import { z } from "zod";
import { getDb } from "./db";
import { upstoxCredentials, botSessions, tradeLog } from "../drizzle/schema";
import { eq, desc, and } from "drizzle-orm";
import { startBot, stopBot, getBotState } from "./botEngine";

// Session token schema — a UUID string generated by the browser and stored in localStorage
const sessionTokenSchema = z.string().min(8).max(128);

export const appRouter = router({
  system: systemRouter,

  // Auth stub (kept for compatibility, always returns null — no Manus login needed)
  auth: router({
    me: publicProcedure.query(() => null),
    logout: publicProcedure.mutation(() => ({ success: true } as const)),
  }),

  // Credentials
  credentials: router({
    get: publicProcedure
      .input(z.object({ sessionToken: sessionTokenSchema }))
      .query(async ({ input }) => {
        const db = await getDb();
        if (!db) return null;
        const rows = await db
          .select()
          .from(upstoxCredentials)
          .where(eq(upstoxCredentials.sessionToken, input.sessionToken))
          .limit(1);
        if (rows.length === 0) return null;
        const row = rows[0];
        return {
          id: row.id,
          apiKey: row.apiKey,
          apiSecretMasked: row.apiSecret.slice(0, 4) + "****",
          hasAccessToken: !!row.accessToken,
          tokenExpiresAt: row.tokenExpiresAt,
          redirectUri: row.redirectUri,
        };
      }),

    save: publicProcedure
      .input(z.object({
        sessionToken: sessionTokenSchema,
        apiKey: z.string().min(1),
        apiSecret: z.string().min(1),
        redirectUri: z.string().optional(),
      }))
      .mutation(async ({ input }) => {
        const db = await getDb();
        if (!db) throw new Error("DB unavailable");
        const existing = await db
          .select({ id: upstoxCredentials.id })
          .from(upstoxCredentials)
          .where(eq(upstoxCredentials.sessionToken, input.sessionToken))
          .limit(1);
        if (existing.length > 0) {
          await db
            .update(upstoxCredentials)
            .set({ apiKey: input.apiKey, apiSecret: input.apiSecret, redirectUri: input.redirectUri })
            .where(eq(upstoxCredentials.sessionToken, input.sessionToken));
        } else {
          await db.insert(upstoxCredentials).values({
            sessionToken: input.sessionToken,
            apiKey: input.apiKey,
            apiSecret: input.apiSecret,
            redirectUri: input.redirectUri,
          });
        }
        return { success: true };
      }),

    saveAccessToken: publicProcedure
      .input(z.object({
        sessionToken: sessionTokenSchema,
        accessToken: z.string().min(1),
      }))
      .mutation(async ({ input }) => {
        const db = await getDb();
        if (!db) throw new Error("DB unavailable");
        const expires = new Date(Date.now() + 24 * 60 * 60 * 1000);
        await db
          .update(upstoxCredentials)
          .set({ accessToken: input.accessToken, tokenExpiresAt: expires })
          .where(eq(upstoxCredentials.sessionToken, input.sessionToken));
        return { success: true };
      }),

    // Exchange Upstox authorization code for access token automatically
    exchangeCode: publicProcedure
      .input(z.object({
        sessionToken: sessionTokenSchema,
        code: z.string().min(1),
        redirectUri: z.string().min(1),
      }))
      .mutation(async ({ input }) => {
        const db = await getDb();
        if (!db) throw new Error("DB unavailable");

        // Load stored API key and secret for this session
        const rows = await db
          .select()
          .from(upstoxCredentials)
          .where(eq(upstoxCredentials.sessionToken, input.sessionToken))
          .limit(1);

        if (rows.length === 0 || !rows[0].apiKey || !rows[0].apiSecret) {
          throw new Error("API Key and Secret not found. Please save them in Settings first.");
        }

        const { apiKey, apiSecret } = rows[0];

        // Call Upstox token endpoint
        const params = new URLSearchParams({
          code: input.code,
          client_id: apiKey,
          client_secret: apiSecret,
          redirect_uri: input.redirectUri,
          grant_type: "authorization_code",
        });

        const response = await fetch("https://api.upstox.com/v2/login/authorization/token", {
          method: "POST",
          headers: {
            "Content-Type": "application/x-www-form-urlencoded",
            "Accept": "application/json",
          },
          body: params.toString(),
        });

        if (!response.ok) {
          const errText = await response.text();
          throw new Error(`Upstox token exchange failed: ${response.status} — ${errText}`);
        }

        const data = await response.json() as { access_token?: string; extended_token?: string };
        if (!data.access_token) {
          throw new Error("Upstox did not return an access token. Please try again.");
        }

        // Save the access token
        const expires = new Date(Date.now() + 24 * 60 * 60 * 1000);
        await db
          .update(upstoxCredentials)
          .set({ accessToken: data.access_token, tokenExpiresAt: expires })
          .where(eq(upstoxCredentials.sessionToken, input.sessionToken));

        return { success: true, userName: undefined };
      }),
  }),

  // Bot
  bot: router({
    status: publicProcedure
      .input(z.object({ sessionToken: sessionTokenSchema }))
      .query(async ({ input }) => {
        const db = await getDb();
        if (!db) return null;
        const rows = await db
          .select()
          .from(botSessions)
          .where(eq(botSessions.sessionToken, input.sessionToken))
          .orderBy(desc(botSessions.updatedAt))
          .limit(1);
        const inMem = getBotState(input.sessionToken);
        if (rows.length === 0) return null;
        return {
          ...rows[0],
          lastPrice: inMem?.lastPrice ?? 0,
          lastSignal: inMem?.lastSignal ?? null,
        };
      }),

    start: publicProcedure
      .input(z.object({
        sessionToken: sessionTokenSchema,
        instrumentToken: z.string().default("NSE_EQ|INE009A01021"),
        instrumentSymbol: z.string().default("RELIANCE"),
        mode: z.enum(["paper", "live"]).default("paper"),
        capital: z.number().default(100000),
        riskPerTradePct: z.number().default(1.0),
        maxTradesPerDay: z.number().default(5),
        dailyLossLimitPct: z.number().default(3.0),
      }))
      .mutation(async ({ input }) => {
        const db = await getDb();
        if (!db) throw new Error("DB unavailable");
        let accessToken: string | null = null;
        if (input.mode === "live") {
          const creds = await db
            .select()
            .from(upstoxCredentials)
            .where(eq(upstoxCredentials.sessionToken, input.sessionToken))
            .limit(1);
          if (creds.length === 0 || !creds[0].accessToken) {
            throw new Error("No Upstox access token. Connect your account first.");
          }
          accessToken = creds[0].accessToken;
        }
        const existing = await db
          .select({ id: botSessions.id })
          .from(botSessions)
          .where(eq(botSessions.sessionToken, input.sessionToken))
          .limit(1);
        let sessionId: number;
        if (existing.length > 0) {
          sessionId = existing[0].id;
          await db
            .update(botSessions)
            .set({
              status: "running",
              mode: input.mode,
              instrumentToken: input.instrumentToken,
              instrumentSymbol: input.instrumentSymbol,
              capital: input.capital,
              riskPerTradePct: input.riskPerTradePct,
              maxTradesPerDay: input.maxTradesPerDay,
              dailyLossLimitPct: input.dailyLossLimitPct,
              tradesCount: 0,
              dailyPnl: 0,
              startedAt: new Date(),
              stoppedAt: null,
              lastError: null,
            })
            .where(eq(botSessions.sessionToken, input.sessionToken));
        } else {
          const result = await db.insert(botSessions).values({
            sessionToken: input.sessionToken,
            status: "running",
            mode: input.mode,
            instrumentToken: input.instrumentToken,
            instrumentSymbol: input.instrumentSymbol,
            capital: input.capital,
            riskPerTradePct: input.riskPerTradePct,
            maxTradesPerDay: input.maxTradesPerDay,
            dailyLossLimitPct: input.dailyLossLimitPct,
            tradesCount: 0,
            dailyPnl: 0,
            startedAt: new Date(),
          });
          sessionId = Number((result as unknown as { insertId: number }).insertId);
        }
        startBot(
          {
            sessionToken: input.sessionToken,
            sessionId,
            status: "running",
            mode: input.mode,
            instrumentToken: input.instrumentToken,
            instrumentSymbol: input.instrumentSymbol,
            capital: input.capital,
            riskPerTradePct: input.riskPerTradePct,
            maxTradesPerDay: input.maxTradesPerDay,
            dailyLossLimitPct: input.dailyLossLimitPct,
            tradesCount: 0,
            dailyPnl: 0,
            accessToken,
          },
          async (trade) => {
            const dbInner = await getDb();
            if (!dbInner) return;
            await dbInner.insert(tradeLog).values({
              sessionToken: input.sessionToken,
              sessionId,
              ...trade,
            });
            const state = getBotState(input.sessionToken);
            if (state) {
              await dbInner
                .update(botSessions)
                .set({
                  tradesCount: state.tradesCount,
                  dailyPnl: state.dailyPnl,
                  lastSignal: state.lastSignal?.direction,
                  lastSignalAt: new Date(),
                  status: state.status,
                  lastError: state.lastError,
                })
                .where(eq(botSessions.sessionToken, input.sessionToken));
            }
          }
        );
        return { success: true, sessionId };
      }),

    stop: publicProcedure
      .input(z.object({ sessionToken: sessionTokenSchema }))
      .mutation(async ({ input }) => {
        stopBot(input.sessionToken);
        const db = await getDb();
        if (db) {
          await db
            .update(botSessions)
            .set({ status: "stopped", stoppedAt: new Date() })
            .where(eq(botSessions.sessionToken, input.sessionToken));
        }
        return { success: true };
      }),

    liveData: publicProcedure
      .input(z.object({ sessionToken: sessionTokenSchema }))
      .query(({ input }) => {
        const state = getBotState(input.sessionToken);
        if (!state) return { price: 0, signal: null, candles: [] };
        return {
          price: state.lastPrice,
          signal: state.lastSignal,
          candles: state.candles.slice(-30),
        };
      }),
  }),

  // Trades
  trades: router({
    list: publicProcedure
      .input(z.object({
        sessionToken: sessionTokenSchema,
        limit: z.number().default(50),
      }))
      .query(async ({ input }) => {
        const db = await getDb();
        if (!db) return [];
        return db
          .select()
          .from(tradeLog)
          .where(eq(tradeLog.sessionToken, input.sessionToken))
          .orderBy(desc(tradeLog.enteredAt))
          .limit(input.limit);
      }),

    stats: publicProcedure
      .input(z.object({ sessionToken: sessionTokenSchema }))
      .query(async ({ input }) => {
        const db = await getDb();
        if (!db) return { totalTrades: 0, wins: 0, losses: 0, winRate: 0, totalPnl: 0, avgPnl: 0 };
        const trades = await db
          .select()
          .from(tradeLog)
          .where(and(
            eq(tradeLog.sessionToken, input.sessionToken),
            eq(tradeLog.status, "closed"),
          ));
        const totalTrades = trades.length;
        const wins = trades.filter((t) => (t.pnl ?? 0) > 0).length;
        const losses = trades.filter((t) => (t.pnl ?? 0) < 0).length;
        const totalPnl = trades.reduce((a, t) => a + (t.pnl ?? 0), 0);
        return {
          totalTrades,
          wins,
          losses,
          winRate: totalTrades > 0 ? (wins / totalTrades) * 100 : 0,
          totalPnl,
          avgPnl: totalTrades > 0 ? totalPnl / totalTrades : 0,
        };
      }),
  }),
});

export type AppRouter = typeof appRouter;
