import { systemRouter } from "./_core/systemRouter";
import { publicProcedure, router } from "./_core/trpc";
import { z } from "zod";
import { getDb } from "./db";
import { upstoxCredentials, botSessions, tradeLog } from "../drizzle/schema";
import { eq, desc, and } from "drizzle-orm";
import { startBot, stopBot, getBotState, placeUpstoxOrder } from "./botEngine";
import { COOKIE_NAME } from "../shared/const";

// Session token schema — a UUID string generated by the browser and stored in localStorage
const sessionTokenSchema = z.string().min(8).max(128);

export const appRouter = router({
  system: systemRouter,

  // Auth stub (kept for compatibility, always returns null — no Manus login needed)
  auth: router({
    me: publicProcedure.query(() => null),
    logout: publicProcedure.mutation(({ ctx }) => {
      // Clear the session cookie so the auth.logout test passes
      try {
        ctx.res.clearCookie(COOKIE_NAME, {
          maxAge: -1,
          secure: true,
          sameSite: "none",
          httpOnly: true,
          path: "/",
        });
      } catch { /* no-op in test env */ }
      return { success: true } as const;
    }),
  }),

  // Credentials
  credentials: router({
    get: publicProcedure
      .input(z.object({ sessionToken: sessionTokenSchema }))
      .query(async ({ input }) => {
        const db = await getDb();
        if (!db) return null;
        const rows = await db
          .select()
          .from(upstoxCredentials)
          .where(eq(upstoxCredentials.sessionToken, input.sessionToken))
          .limit(1);
        if (rows.length === 0) return null;
        const row = rows[0];
        return {
          id: row.id,
          apiKey: row.apiKey,
          apiSecretMasked: row.apiSecret.slice(0, 4) + "****",
          hasAccessToken: !!row.accessToken,
          tokenExpiresAt: row.tokenExpiresAt,
          redirectUri: row.redirectUri,
        };
      }),

    save: publicProcedure
      .input(z.object({
        sessionToken: sessionTokenSchema,
        apiKey: z.string().min(1),
        apiSecret: z.string().min(1),
        redirectUri: z.string().optional(),
      }))
      .mutation(async ({ input }) => {
        const db = await getDb();
        if (!db) throw new Error("DB unavailable");
        const existing = await db
          .select({ id: upstoxCredentials.id })
          .from(upstoxCredentials)
          .where(eq(upstoxCredentials.sessionToken, input.sessionToken))
          .limit(1);
        if (existing.length > 0) {
          await db
            .update(upstoxCredentials)
            .set({ apiKey: input.apiKey, apiSecret: input.apiSecret, redirectUri: input.redirectUri })
            .where(eq(upstoxCredentials.sessionToken, input.sessionToken));
        } else {
          await db.insert(upstoxCredentials).values({
            sessionToken: input.sessionToken,
            apiKey: input.apiKey,
            apiSecret: input.apiSecret,
            redirectUri: input.redirectUri,
          });
        }
        return { success: true };
      }),

    saveAccessToken: publicProcedure
      .input(z.object({
        sessionToken: sessionTokenSchema,
        accessToken: z.string().min(1),
      }))
      .mutation(async ({ input }) => {
        const db = await getDb();
        if (!db) throw new Error("DB unavailable");
        const expires = new Date(Date.now() + 24 * 60 * 60 * 1000);
        await db
          .update(upstoxCredentials)
          .set({ accessToken: input.accessToken, tokenExpiresAt: expires })
          .where(eq(upstoxCredentials.sessionToken, input.sessionToken));
        return { success: true };
      }),

    exchangeCode: publicProcedure
      .input(z.object({
        sessionToken: sessionTokenSchema,
        code: z.string().min(1),
        redirectUri: z.string().min(1),
      }))
      .mutation(async ({ input }) => {
        const db = await getDb();
        if (!db) throw new Error("DB unavailable");

        const rows = await db
          .select()
          .from(upstoxCredentials)
          .where(eq(upstoxCredentials.sessionToken, input.sessionToken))
          .limit(1);

        if (rows.length === 0 || !rows[0].apiKey || !rows[0].apiSecret) {
          throw new Error("API Key and Secret not found. Please save them in Settings first.");
        }

        const { apiKey, apiSecret } = rows[0];

        const params = new URLSearchParams({
          code: input.code,
          client_id: apiKey,
          client_secret: apiSecret,
          redirect_uri: input.redirectUri,
          grant_type: "authorization_code",
        });

        const response = await fetch("https://api.upstox.com/v2/login/authorization/token", {
          method: "POST",
          headers: {
            "Content-Type": "application/x-www-form-urlencoded",
            "Accept": "application/json",
          },
          body: params.toString(),
        });

        if (!response.ok) {
          const errText = await response.text();
          throw new Error(`Upstox token exchange failed: ${response.status} — ${errText}`);
        }

        const data = await response.json() as { access_token?: string };
        if (!data.access_token) {
          throw new Error("Upstox did not return an access token. Please try again.");
        }

        const expires = new Date(Date.now() + 24 * 60 * 60 * 1000);
        await db
          .update(upstoxCredentials)
          .set({ accessToken: data.access_token, tokenExpiresAt: expires })
          .where(eq(upstoxCredentials.sessionToken, input.sessionToken));

        return { success: true };
      }),
  }),

  // Bot
  bot: router({
    status: publicProcedure
      .input(z.object({ sessionToken: sessionTokenSchema }))
      .query(async ({ input }) => {
        const db = await getDb();
        if (!db) return null;
        const rows = await db
          .select()
          .from(botSessions)
          .where(eq(botSessions.sessionToken, input.sessionToken))
          .orderBy(desc(botSessions.updatedAt))
          .limit(1);
        const inMem = getBotState(input.sessionToken);
        if (rows.length === 0) return null;
        const row = rows[0];
        return {
          ...row,
          lastPrice: inMem?.lastPrice ?? row.lastPrice ?? 0,
          bidPrice: inMem?.bidPrice ?? row.bidPrice ?? 0,
          askPrice: inMem?.askPrice ?? row.askPrice ?? 0,
          lastSignal: inMem?.lastSignal ?? null,
          nextScanAt: inMem?.nextScanAt ?? row.nextScanAt ?? 0,
          openTrade: inMem?.openTrade ?? null,
        };
      }),

    start: publicProcedure
      .input(z.object({
        sessionToken: sessionTokenSchema,
        instrumentToken: z.string().default("NSE_EQ|INE009A01021"),
        instrumentSymbol: z.string().default("RELIANCE"),
        instrumentLabel: z.string().default("Reliance Industries"),
        mode: z.enum(["paper", "live"]).default("paper"),
        capital: z.number().default(100000),
        riskPerTradePct: z.number().default(1.0),
        maxTradesPerDay: z.number().default(5),
        dailyLossLimitPct: z.number().default(3.0),
        stopLossMultiplier: z.number().default(1.5),
        targetMultiplier: z.number().default(3.0),
        trailingSlEnabled: z.boolean().default(false),
        trailingSlPct: z.number().default(0.5),
        minConfidence: z.number().default(60),
        scanIntervalSec: z.number().default(60),
      }))
      .mutation(async ({ input }) => {
        const db = await getDb();
        if (!db) throw new Error("DB unavailable");
        let accessToken: string | null = null;
        if (input.mode === "live") {
          const creds = await db
            .select()
            .from(upstoxCredentials)
            .where(eq(upstoxCredentials.sessionToken, input.sessionToken))
            .limit(1);
          if (creds.length === 0 || !creds[0].accessToken) {
            throw new Error("No Upstox access token. Connect your account first.");
          }
          accessToken = creds[0].accessToken;
        }

        // Check for existing open trade to restore
        const existingOpenTrades = await db
          .select()
          .from(tradeLog)
          .where(and(
            eq(tradeLog.sessionToken, input.sessionToken),
            eq(tradeLog.status, "open"),
          ))
          .orderBy(desc(tradeLog.enteredAt))
          .limit(1);

        let existingOpenTrade = null;
        if (existingOpenTrades.length > 0) {
          const t = existingOpenTrades[0];
          const slDist0 = Math.abs((t.entryPrice ?? 0) - (t.slPrice ?? 0));
          existingOpenTrade = {
            dbId: t.id,
            symbol: t.symbol,
            symbolLabel: t.symbolLabel ?? t.symbol,
            instrumentToken: t.instrumentToken ?? input.instrumentToken,
            direction: t.direction,
            mode: t.mode,
            entryPrice: t.entryPrice,
            quantity: t.quantity,
            slPrice: t.slPrice ?? 0,
            targetPrice: t.targetPrice ?? 0,
            atr: t.atr ?? 0,
            confidence: t.confidence ?? 0,
            upstoxOrderId: t.upstoxOrderId ?? undefined,
            enteredAt: t.enteredAt,
            trailingSlEnabled: input.trailingSlEnabled,
            trailingSlPct: input.trailingSlPct,
            currentSl: t.slPrice ?? 0,
            partial1RPrice: t.direction === "BUY" ? t.entryPrice + slDist0 : t.entryPrice - slDist0,
            partial2RPrice: t.direction === "BUY" ? t.entryPrice + slDist0 * 2 : t.entryPrice - slDist0 * 2,
            partialBooked: 0 as 0 | 1 | 2,
            bookedQty: 0,
            bookedPnl: 0,
          };
        }

        const existing = await db
          .select({ id: botSessions.id })
          .from(botSessions)
          .where(eq(botSessions.sessionToken, input.sessionToken))
          .limit(1);

        let sessionId: number;
        if (existing.length > 0) {
          sessionId = existing[0].id;
          await db
            .update(botSessions)
            .set({
              status: "running",
              mode: input.mode,
              instrumentToken: input.instrumentToken,
              instrumentSymbol: input.instrumentSymbol,
              instrumentLabel: input.instrumentLabel,
              capital: input.capital,
              riskPerTradePct: input.riskPerTradePct,
              maxTradesPerDay: input.maxTradesPerDay,
              dailyLossLimitPct: input.dailyLossLimitPct,
              stopLossMultiplier: input.stopLossMultiplier,
              targetMultiplier: input.targetMultiplier,
              trailingSlEnabled: input.trailingSlEnabled,
              trailingSlPct: input.trailingSlPct,
              minConfidence: input.minConfidence,
              scanIntervalSec: input.scanIntervalSec,
              tradesCount: 0,
              dailyPnl: 0,
              startedAt: new Date(),
              stoppedAt: null,
              lastError: null,
            })
            .where(eq(botSessions.sessionToken, input.sessionToken));
        } else {
          const result = await db.insert(botSessions).values({
            sessionToken: input.sessionToken,
            status: "running",
            mode: input.mode,
            instrumentToken: input.instrumentToken,
            instrumentSymbol: input.instrumentSymbol,
            instrumentLabel: input.instrumentLabel,
            capital: input.capital,
            riskPerTradePct: input.riskPerTradePct,
            maxTradesPerDay: input.maxTradesPerDay,
            dailyLossLimitPct: input.dailyLossLimitPct,
            stopLossMultiplier: input.stopLossMultiplier,
            targetMultiplier: input.targetMultiplier,
            trailingSlEnabled: input.trailingSlEnabled,
            trailingSlPct: input.trailingSlPct,
            minConfidence: input.minConfidence,
            scanIntervalSec: input.scanIntervalSec,
            tradesCount: 0,
            dailyPnl: 0,
            startedAt: new Date(),
          });
          sessionId = Number((result as unknown as { insertId: number }).insertId);
        }

        // Trade open callback — inserts into DB and returns the new row ID
        const onTradeOpen = async (trade: {
          symbol: string;
          symbolLabel: string;
          instrumentToken: string;
          direction: "BUY" | "SELL";
          mode: "paper" | "live";
          entryPrice: number;
          quantity: number;
          slPrice: number;
          targetPrice: number;
          atr: number;
          confidence: number;
          status: "open" | "closed" | "cancelled";
          upstoxOrderId?: string;
          signalReason: string;
          enteredAt: Date;
        }): Promise<number> => {
          const dbInner = await getDb();
          if (!dbInner) return 0;
          const result = await dbInner.insert(tradeLog).values({
            sessionToken: input.sessionToken,
            sessionId,
            ...trade,
          });
          const insertId = Number((result as unknown as { insertId: number }).insertId);

          // Update session stats
          const state = getBotState(input.sessionToken);
          if (state) {
            await dbInner
              .update(botSessions)
              .set({
                tradesCount: state.tradesCount,
                dailyPnl: state.dailyPnl,
                lastSignal: state.lastSignal?.direction,
                lastSignalAt: new Date(),
                lastPrice: state.lastPrice,
                bidPrice: state.bidPrice,
                askPrice: state.askPrice,
                status: state.status,
                lastError: state.lastError,
              })
              .where(eq(botSessions.sessionToken, input.sessionToken));
          }
          return insertId;
        };

        // Trade close callback — updates the trade row with exit data
        const onTradeClose = async (dbId: number, exitPrice: number, pnl: number, exitReason: string): Promise<void> => {
          const dbInner = await getDb();
          if (!dbInner) return;
          const entryRow = await dbInner
            .select({ entryPrice: tradeLog.entryPrice, quantity: tradeLog.quantity, capital: botSessions.capital })
            .from(tradeLog)
            .where(eq(tradeLog.id, dbId))
            .limit(1);
          const capital = entryRow[0]?.capital ?? input.capital;
          await dbInner
            .update(tradeLog)
            .set({
              status: "closed",
              exitPrice,
              pnl,
              pnlPct: (pnl / capital) * 100,
              exitReason,
              exitedAt: new Date(),
            })
            .where(eq(tradeLog.id, dbId));

          const state = getBotState(input.sessionToken);
          if (state) {
            await dbInner
              .update(botSessions)
              .set({
                tradesCount: state.tradesCount,
                dailyPnl: state.dailyPnl,
                lastPrice: state.lastPrice,
                bidPrice: state.bidPrice,
                askPrice: state.askPrice,
                status: state.status,
                lastError: state.lastError,
              })
              .where(eq(botSessions.sessionToken, input.sessionToken));
          }
        };

        startBot(
          {
            sessionToken: input.sessionToken,
            sessionId,
            status: "running",
            mode: input.mode,
            instrumentToken: input.instrumentToken,
            instrumentSymbol: input.instrumentSymbol,
            instrumentLabel: input.instrumentLabel,
            capital: input.capital,
            riskPerTradePct: input.riskPerTradePct,
            maxTradesPerDay: input.maxTradesPerDay,
            dailyLossLimitPct: input.dailyLossLimitPct,
            stopLossMultiplier: input.stopLossMultiplier,
            targetMultiplier: input.targetMultiplier,
            trailingSlEnabled: input.trailingSlEnabled,
            trailingSlPct: input.trailingSlPct,
            minConfidence: input.minConfidence,
            scanIntervalSec: input.scanIntervalSec,
            tradesCount: 0,
            dailyPnl: 0,
            accessToken,
          },
          onTradeOpen,
          onTradeClose,
          existingOpenTrade,
        );

        return { success: true, sessionId };
      }),

    stop: publicProcedure
      .input(z.object({ sessionToken: sessionTokenSchema }))
      .mutation(async ({ input }) => {
        stopBot(input.sessionToken);
        const db = await getDb();
        if (db) {
          await db
            .update(botSessions)
            .set({ status: "stopped", stoppedAt: new Date() })
            .where(eq(botSessions.sessionToken, input.sessionToken));
        }
        return { success: true };
      }),

    liveData: publicProcedure
      .input(z.object({ sessionToken: sessionTokenSchema }))
      .query(async ({ input }) => {
        const state = getBotState(input.sessionToken);
        if (!state) {
          // Fallback: read last known price from DB
          const db = await getDb();
          if (!db) return { price: 0, bid: 0, ask: 0, signal: null, candles: [], nextScanAt: 0, openTrade: null };
          const rows = await db
            .select()
            .from(botSessions)
            .where(eq(botSessions.sessionToken, input.sessionToken))
            .limit(1);
          if (rows.length === 0) return { price: 0, bid: 0, ask: 0, signal: null, candles: [], nextScanAt: 0, openTrade: null };
          return {
            price: rows[0].lastPrice ?? 0,
            bid: rows[0].bidPrice ?? 0,
            ask: rows[0].askPrice ?? 0,
            signal: null,
            candles: [],
            nextScanAt: rows[0].nextScanAt ?? 0,
            openTrade: null,
          };
        }
        return {
          price: state.lastPrice,
          bid: state.bidPrice,
          ask: state.askPrice,
          signal: state.lastSignal,
          candles: state.candles.slice(-60),
          candles5mCount: state.candles5m.length,
          nextScanAt: state.nextScanAt,
          openTrade: state.openTrade,
          isPowerHourMode: state.isPowerHourMode,
          isMCXEveningMode: state.isMCXEveningMode,
          heroZeroMode: state.heroZeroMode,
          reEntryCandles: state.reEntryCandles,
        };
      }),

    manualExit: publicProcedure
      .input(z.object({
        sessionToken: sessionTokenSchema,
        tradeId: z.number(),
        exitPrice: z.number(),
      }))
      .mutation(async ({ input }) => {
        const db = await getDb();
        if (!db) throw new Error("DB unavailable");

        // Load trade
        const trades = await db
          .select()
          .from(tradeLog)
          .where(and(eq(tradeLog.id, input.tradeId), eq(tradeLog.sessionToken, input.sessionToken)))
          .limit(1);
        if (trades.length === 0) throw new Error("Trade not found");
        const trade = trades[0];

        const pnl = trade.direction === "BUY"
          ? (input.exitPrice - trade.entryPrice) * trade.quantity
          : (trade.entryPrice - input.exitPrice) * trade.quantity;

        // Place real exit order in live mode
        let orderId: string | null = null;
        if (trade.mode === "live") {
          const creds = await db
            .select()
            .from(upstoxCredentials)
            .where(eq(upstoxCredentials.sessionToken, input.sessionToken))
            .limit(1);
          if (creds.length > 0 && creds[0].accessToken && trade.instrumentToken) {
            const exitDir = trade.direction === "BUY" ? "SELL" : "BUY";
            orderId = await placeUpstoxOrder(creds[0].accessToken, trade.instrumentToken, exitDir, trade.quantity);
          }
        }

        const session = await db
          .select({ capital: botSessions.capital })
          .from(botSessions)
          .where(eq(botSessions.sessionToken, input.sessionToken))
          .limit(1);
        const capital = session[0]?.capital ?? 100000;

        await db
          .update(tradeLog)
          .set({
            status: "closed",
            exitPrice: input.exitPrice,
            pnl,
            pnlPct: (pnl / capital) * 100,
            exitReason: "Manual Exit",
            exitedAt: new Date(),
            upstoxOrderId: orderId ?? trade.upstoxOrderId ?? undefined,
          })
          .where(eq(tradeLog.id, input.tradeId));

        // Clear from in-memory bot state
        const state = getBotState(input.sessionToken);
        if (state?.openTrade?.dbId === input.tradeId) {
          state.openTrade = null;
          state.dailyPnl += pnl;
        }

        return { success: true, pnl, orderId };
      }),
  }),

  // Trades
  trades: router({
    list: publicProcedure
      .input(z.object({
        sessionToken: sessionTokenSchema,
        limit: z.number().default(50),
      }))
      .query(async ({ input }) => {
        const db = await getDb();
        if (!db) return [];
        return db
          .select()
          .from(tradeLog)
          .where(eq(tradeLog.sessionToken, input.sessionToken))
          .orderBy(desc(tradeLog.enteredAt))
          .limit(input.limit);
      }),

    openTrade: publicProcedure
      .input(z.object({ sessionToken: sessionTokenSchema }))
      .query(async ({ input }) => {
        const db = await getDb();
        if (!db) return null;
        const rows = await db
          .select()
          .from(tradeLog)
          .where(and(
            eq(tradeLog.sessionToken, input.sessionToken),
            eq(tradeLog.status, "open"),
          ))
          .orderBy(desc(tradeLog.enteredAt))
          .limit(1);
        return rows.length > 0 ? rows[0] : null;
      }),

    stats: publicProcedure
      .input(z.object({ sessionToken: sessionTokenSchema }))
      .query(async ({ input }) => {
        const db = await getDb();
        if (!db) return { totalTrades: 0, wins: 0, losses: 0, winRate: 0, totalPnl: 0, avgPnl: 0 };
        const trades = await db
          .select()
          .from(tradeLog)
          .where(and(
            eq(tradeLog.sessionToken, input.sessionToken),
            eq(tradeLog.status, "closed"),
          ));
        const totalTrades = trades.length;
        const wins = trades.filter((t: typeof trades[0]) => (t.pnl ?? 0) > 0).length;
        const losses = trades.filter((t: typeof trades[0]) => (t.pnl ?? 0) < 0).length;
        const totalPnl = trades.reduce((a: number, t: typeof trades[0]) => a + (t.pnl ?? 0), 0);
        return {
          totalTrades,
          wins,
          losses,
          winRate: totalTrades > 0 ? (wins / totalTrades) * 100 : 0,
          totalPnl,
          avgPnl: totalTrades > 0 ? totalPnl / totalTrades : 0,
        };
      }),

    todayStats: publicProcedure
      .input(z.object({ sessionToken: sessionTokenSchema }))
      .query(async ({ input }) => {
        const db = await getDb();
        if (!db) return { todayTrades: 0, todayPnl: 0, wins: 0, losses: 0, winRate: 0 };
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        const trades = await db
          .select()
          .from(tradeLog)
          .where(and(
            eq(tradeLog.sessionToken, input.sessionToken),
            eq(tradeLog.status, "closed"),
          ));
        const todayTrades = trades.filter((t: typeof trades[0]) => new Date(t.enteredAt) >= today);
        const wins = todayTrades.filter((t: typeof trades[0]) => (t.pnl ?? 0) > 0).length;
        const losses = todayTrades.filter((t: typeof trades[0]) => (t.pnl ?? 0) < 0).length;
        const todayPnl = todayTrades.reduce((a: number, t: typeof trades[0]) => a + (t.pnl ?? 0), 0);
        return {
          todayTrades: todayTrades.length,
          todayPnl,
          wins,
          losses,
          winRate: todayTrades.length > 0 ? (wins / todayTrades.length) * 100 : 0,
        };
      }),
  }),

  // Account — Upstox profile & funds
  account: router({
    profile: publicProcedure
      .input(z.object({ sessionToken: sessionTokenSchema }))
      .query(async ({ input }) => {
        const db = await getDb();
        if (!db) return null;
        const rows = await db
          .select()
          .from(upstoxCredentials)
          .where(eq(upstoxCredentials.sessionToken, input.sessionToken))
          .limit(1);
        if (rows.length === 0 || !rows[0].accessToken) return null;
        const { accessToken } = rows[0];
        try {
          const res = await fetch("https://api.upstox.com/v2/user/profile", {
            headers: {
              Authorization: `Bearer ${accessToken}`,
              Accept: "application/json",
            },
            signal: AbortSignal.timeout(8000),
          });
          if (!res.ok) return null;
          const json = await res.json() as { data?: {
            user_id?: string;
            user_name?: string;
            email?: string;
            mobile_number?: string;
            broker?: string;
            user_type?: string;
            exchanges?: string[];
            products?: string[];
            order_types?: string[];
          } };
          return json.data ?? null;
        } catch {
          return null;
        }
      }),

    balance: publicProcedure
      .input(z.object({ sessionToken: sessionTokenSchema }))
      .query(async ({ input }) => {
        const db = await getDb();
        if (!db) return null;
        const rows = await db
          .select()
          .from(upstoxCredentials)
          .where(eq(upstoxCredentials.sessionToken, input.sessionToken))
          .limit(1);
        if (rows.length === 0 || !rows[0].accessToken) return null;
        const { accessToken } = rows[0];
        try {
          const res = await fetch("https://api.upstox.com/v2/user/get-funds-and-margin", {
            headers: {
              Authorization: `Bearer ${accessToken}`,
              Accept: "application/json",
            },
            signal: AbortSignal.timeout(8000),
          });
          if (!res.ok) return null;
          const json = await res.json() as { data?: {
            equity?: {
              available_margin?: number;
              used_margin?: number;
              payin_amount?: number;
              span_margin?: number;
              adhoc_margin?: number;
              notional_cash?: number;
              available_cash?: number;
              exposure_margin?: number;
            };
            commodity?: {
              available_margin?: number;
              used_margin?: number;
              available_cash?: number;
            };
          } };
          return json.data ?? null;
        } catch {
          return null;
        }
      }),
  }),
});

export type AppRouter = typeof appRouter;
